In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 4], [8, 10, 4]])

In [3]:
# random values from uniform [0-1) distribution
# arguments are dimension sizes
np.random.rand(2, 3)

array([[0.14300095, 0.09891907, 0.31273741],
       [0.67128617, 0.13776151, 0.28370761]])

In [4]:
# same as np.random.rand, but takes shape as tuple
np.random.random((2, 3))
# this function also goes by, random_sample, ranf, sample

array([[0.33185316, 0.96372154, 0.86667304],
       [0.5144591 , 0.54395347, 0.16301334]])

In [5]:
# random values from standard normal distribution mean=0, std=1
# arguments dimension sizes
np.random.randn(2, 3)

array([[-0.39416499, -0.53508471, -0.42556341],
       [ 1.56038675,  1.13293636,  0.64975282]])

In [6]:
# random integer (low inclusive, high exclusive)
np.random.randint(low=10, high=20, size=3)

array([16, 13, 12])

In [7]:
# randomly choose from array-like
nums = [3, 6, 80, 90, 5]

np.random.choice(nums, size=2, replace=False)

array([ 3, 80])

## Distributions
Draw samples from various distributions

-  beta
-  binomial
-  chisquare
-  dirichlet
-  exponential
-  f
-  gamma
-  geometric
-  gumbel
-  hypergeometric
-  laplace
-  logistic
-  lognormal
-  logseries
-  multinomial
-  multivariate_normal
-  negative_binomial
-  noncentral_chisquare
-  noncentral_f
-  normal
-  pareto
-  poisson
-  power
-  rayleigh
-  standard_cauchy
-  standard_exponential
-  standard_gamma
-  standard_normal
-  standard_t
-  triangular
-  uniform
-  vonmises
-  wald
-  weibull
-  zipf


In [8]:
np.random.binomial(n=100, p=.5, size=5)

array([55, 50, 53, 59, 49])