In [1]:
import numpy as np

In [2]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
arr = arr.reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# flatten vs ravel
flatten returns copy, ravel returns view... i.e. you can still modify original array with ravel

In [4]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
# can't modify original array
arr.flatten()[5] = 50
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# can modify original array
arr.ravel()[8] = 80
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7, 80,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Transposing

transpose, swapaxis, moveaxis all do same thing in 2D space

In [8]:
# transposed array
arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3, 80, 13, 18],
       [ 4,  9, 14, 19]])

In [9]:
# swap axes does same thing as transpose in 2D space
ax1, ax2 = 0, 1
arr.swapaxes(ax1, ax2)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3, 80, 13, 18],
       [ 4,  9, 14, 19]])

In [10]:
# moveaxis does same thing as transpose in 2D space
np.moveaxis(arr, source=0, destination=1)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3, 80, 13, 18],
       [ 4,  9, 14, 19]])

# Stacking

## Stacking 1D Arrays

In [11]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)
arr3 = np.arange(20, 25)

# horizontal stacking, concatenating along first axis, like python list + python list
np.hstack((arr1, arr2, arr3))

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24])

In [12]:
np.concatenate((arr1, arr2, arr3), axis=0)

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24])

In [13]:
# vertical stacking, like making list of lists
np.vstack((arr1, arr2, arr3))

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Stacking 2D Arrays

In [14]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)
arr3 = np.arange(20, 25)
arr4 = np.arange(30, 35)

arr1_2d = np.vstack((arr1, arr2))
arr2_2d = np.vstack((arr3, arr4))
print(arr1_2d, '\n\n', arr2_2d)


[[ 0  1  2  3  4]
 [10 11 12 13 14]] 

 [[20 21 22 23 24]
 [30 31 32 33 34]]


In [15]:
# as long as columns (axis 1) are same length we can vstack 2d arrays
np.vstack((arr1_2d, arr2_2d))

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [16]:
# as long as rows (axis 0) are same length we can hstack 2d arrays
np.hstack((arr1_2d, arr2_2d))

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])