In [1]:
import numpy as np

# Averages + Variance

-  median
-  average
-  mean
-  std
-  var
-  nanmedian (ignores nans)
-  nanmean
-  nanstd
-  nanvar

methods with nan in front ignore nan in array. np.nan is different than None

In [2]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
# mean of all values in array
np.mean(arr)

9.5

In [4]:
# mean of each column
np.mean(arr, axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [5]:
# mean of each row
np.mean(arr, axis=1)

array([ 2.,  7., 12., 17.])

In [6]:
a = np.array([np.nan, 1, np.nan, 5, 9, 8])
np.nanmean(a) # np.mean would have returned nan

5.75

In [7]:
np.mean(a)

nan

# Order Statistics
-  amin
-  amax
-  nanmin
-  nanmax
-  ptp
-  percentile
-  nanpercentile
-  quantile
-  nanquantile

## np.percentile

np.percentile default interpolation can lead to slightly unexpected values

In [8]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [9]:
# get 80th percentile of array
np.percentile(arr, 80, interpolation='linear') # linear is default

4.2

In [10]:
# linear interpolation works like this
percentile = .8
idx = (arr.size - 1) * percentile
idx

3.2

In [11]:
# since there is no index 3.2 we take value at index 3 and add 20% of the gap between index 3 val and index 4 val
i = arr[int(idx)]
j = arr[int(idx) + 1]
fraction = idx % 1
i + (j - i)*fraction

4.2

In [12]:
np.percentile(arr, 80, interpolation='midpoint')

4.5

In [13]:
np.percentile(arr, 80, interpolation='lower')

4

In [14]:
np.percentile(arr, 80, interpolation='higher')

5

In [15]:
np.percentile(arr, 80, interpolation='nearest')

4

## np.quantile

In [16]:
arr = np.arange(30)

In [17]:
# passing one num to second arg of quantile is like using percentile

np.quantile(arr, .8, interpolation='linear'), np.percentile(arr, 80, interpolation='linear')
# linear interpolation is default for both functions

(23.200000000000003, 23.200000000000003)

In [18]:
# get cut points corresponding to given percentiles
np.quantile(arr, [.5, .8])

array([14.5, 23.2])

### Other

In [19]:
np.amin(arr), np.amax(arr)

(0, 29)

In [20]:
np.ptp(arr) # equal to max - min

29